baseURL = "http://example.org/"
languageCode = "en-us"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"
defaultContentLanguage = "en"
paginate = 3
googleAnalytics = ""
enableRobotsTXT = true
sectionPagesMenu = "main"
copyright = " "
title = "İbrahim Esen"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    disable = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/iesen"
  instagram = ""
  youtube = ""
  github = "https://github.com/iesen"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/iesen"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  #featured_image = "/static/images/welcome_featured.jpg"
  recent_posts_number = 2

[languages]
  [languages.en]
    weight = 1
    [languages.en.params]
      description  = "Welcome to my software inn"
  [languages.tr]
    weight = 2
    [languages.tr.params]
      description  = "Yazılım dünyama hoşgeldiniz"

